[package]
name = "auryn"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.6.0"
indexmap = "2.12.1"
rustc-hash = "2.1.1"

[dev-dependencies]
insta = { version = "1.44.3", features = ["glob"] }

[lints.clippy]
# This simplifies module management imho
pub_use = "warn"
dbg_macro = "warn"
